
import type { MenuItem, Category } from './types';

export const categories: Category[] = [
  { id: 'cat1', name: 'الوجبات', name_en: 'Meals' },
  { id: 'cat2', name: 'المشروبات', name_en: 'Beverages' },
  { id: 'cat3', name: 'الصوصات', name_en: 'Sauces' },
];

export const menuItems: MenuItem[] = [
  {
    id: 'item1',
    name: 'سلطة فتوش',
    name_en: 'Fattoush Salad',
    description: 'سلطة شرق أوسطية منعشة مع الخبز المحمص.',
    description_en: 'Refreshing Middle Eastern salad with toasted bread.',
    price: 25.00,
    categoryId: 'cat1',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'salad bread',
  },
  {
    id: 'item2',
    name: 'حمص باللحمة',
    name_en: 'Hummus with Meat',
    description: 'حمص كريمي مع قطع اللحم المفروم والصنوبر.',
    description_en: 'Creamy hummus with minced meat and pine nuts.',
    price: 35.00,
    categoryId: 'cat1',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'hummus meat',
  },
  {
    id: 'item3',
    name: 'مشاوي مشكلة',
    name_en: 'Mixed Grill',
    description: 'تشكيلة من الكباب، الشيش طاووق، واللحم المشوي.',
    description_en: 'Assortment of kebab, shish tawook, and grilled meat.',
    price: 90.00,
    categoryId: 'cat1',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'grill kebab',
  },
  {
    id: 'item4',
    name: 'مقلوبة دجاج',
    name_en: 'Chicken Maqluba',
    description: 'أرز مطبوخ مع الدجاج والخضروات المقلية.',
    description_en: 'Rice cooked with chicken and fried vegetables.',
    price: 75.00,
    categoryId: 'cat1',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'rice chicken',
  },
  {
    id: 'item5',
    name: 'كنافة نابلسية',
    name_en: 'Nabulsi Knafeh',
    description: 'طبقات من العجين الناعم والجبنة الحلوة.',
    description_en: 'Layers of soft dough and sweet cheese.',
    price: 40.00,
    categoryId: 'cat1', 
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dessert cheese',
  },
  {
    id: 'item6',
    name: 'بقلاوة مشكلة',
    name_en: 'Mixed Baklava',
    description: 'تشكيلة من الحلويات الشرقية بالفستق والجوز.',
    description_en: 'Assortment of oriental sweets with pistachios and walnuts.',
    price: 30.00,
    categoryId: 'cat1', 
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dessert nuts',
  },
  {
    id: 'item7',
    name: 'ليمون بالنعناع',
    name_en: 'Lemon with Mint',
    description: 'عصير ليمون منعش مع أوراق النعناع الطازجة.',
    description_en: 'Refreshing lemon juice with fresh mint leaves.',
    price: 15.00,
    categoryId: 'cat2',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'juice lemon',
  },
  {
    id: 'item8',
    name: 'قهوة عربية',
    name_en: 'Arabic Coffee',
    description: 'قهوة تقليدية ذات نكهة قوية.',
    description_en: 'Traditional coffee with a strong flavor.',
    price: 10.00,
    categoryId: 'cat2',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'coffee traditional',
  },
  {
    id: 'item9',
    name: 'صوص الثوم',
    name_en: 'Garlic Sauce',
    description: 'صوص ثوم كريمي.',
    description_en: 'Creamy garlic sauce.',
    price: 5.00,
    categoryId: 'cat3',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'garlic sauce',
  },
  {
    id: 'item10',
    name: 'صوص الطحينة',
    name_en: 'Tahini Sauce',
    description: 'صوص طحينة كلاسيكي.',
    description_en: 'Classic tahini sauce.',
    price: 5.00,
    categoryId: 'cat3',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'tahini sauce',
  },
  {
    id: 'item11',
    name: 'بيبسي',
    name_en: 'Pepsi',
    description: 'مشروب غازي منعش.',
    description_en: 'Refreshing carbonated drink.',
    price: 5.00,
    categoryId: 'cat2',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'soda can',
  },
  {
    id: 'item12',
    name: 'ماء معدني',
    name_en: 'Mineral Water',
    description: 'ماء شرب نقي.',
    description_en: 'Pure drinking water.',
    price: 3.00,
    categoryId: 'cat2',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'water bottle',
  },
];
